services:
  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/db.sqlite
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    ports:
      - "5173:5173" # Puerto común de Vite
    volumes:
      - ./frontend:/app
      # Evita que el volumen pise las librerías instaladas en el contenedor
      - /app/node_modules 
    environment:
      - VITE_API_URL=http://localhost:8000